### ISSUE TITLE
Pashchim Champaran - Valmiki Nagar AC done

### ISSUE THREAD

**Issue by NishaT** [datameet/Bihar-AC-Election-Report-Cards#13]

**Comment by thejeshgn** [comment]
@NishaT 
There are 93 PDFs but only 54 CSVs. Is that fine?

**Comment by NishaT** [comment]
@thejeshgn Yes there was a mistake with the uploading of the PDFs half of them belong to another AC

**Comment by thejeshgn** [comment]
https://github.com/datameet/Bihar-AC-Election-Report-Cards/tree/master/data/cleaned/pashchim_champaran/valmiki_nagar

**Comment by thejeshgn** [comment]
Done
