### ISSUE TITLE
PRIORITY - Add sanitation data to Lauriya District

### ISSUE THREAD

**Issue by NishaT** [datameet/Bihar-AC-Election-Report-Cards#14]
https://www.dropbox.com/s/ccin6ai4l2c7qu8/Sanitation%20-%20Jogapatti.xlsx?dl=0
https://www.dropbox.com/s/q7baq927c6f1o75/Sanitation%20-%20Lauriya.xlsx?dl=0

**Comment by thejeshgn** [comment]
Done

https://github.com/datameet/Bihar-AC-Election-Report-Cards/blob/master/data/cleaned/pashchim_champaran/Lauriya/Pashchim_Champaran__Lauriya__Sanitation.csv
