### ISSUE TITLE
Bagaha AC correction

### ISSUE THREAD

**Issue by NishaT** [datameet/Bihar-AC-Election-Report-Cards#15]
Bagaha AC includes the following GPs
Kharhat Trivawni
Chambaliya,
Bairagi Sonbarsa
Bairati Bariyarwa
Paikbaliya Marjadpur

They are currently listed in Valmiki nagar data.

**Comment by thejeshgn** [comment]
Moved...

**Comment by thejeshgn** [comment]
Checked the sanitation. These dont exist in Valmiki nagar sanitation data.

**Comment by NishaT** [comment]
Bagaha was correct in the analysis

On Wed, Oct 28, 2015 at 9:18 AM, Thejesh GN notifications@github.com
wrote:

> Checked the sanitation. These dont exist in Valmiki nagar sanitation data.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datameet/Bihar-AC-Election-Report-Cards/issues/15#issuecomment-151714562
> .

## 

Nisha Thompson
Mobile: 962-061-2245
