### ISSUE TITLE
Chanpatia AC Correction

### ISSUE THREAD

**Issue by NishaT** [datameet/Bihar-AC-Election-Report-Cards#17]
These are teh GPs from MAJHALIA that belong in Chanpatia AC

RATAN MALA
CHANAIN BANDH
SARISWA
BARWASI MRAGHAT
MAHNA GANNI
DHOKRAHA
HARPUR GADHWA
MAHNWA RAMPURWA
DUMRI
NAUTAN KHURD
BAITHANI ABHNACHAK

Right now there are too many GPs from MAJHALIA in the files right now

Also I have put new GPs in that were not there before
AURIA
BAKULAPUR
BANKAT PURAIHA
BHAISAHI POKHARIA
CHARGAHA
CHUHRI
KURWA MATHIA
RAHIPUR RAMPURVA

Please check teh water quality and sanitation data

**Comment by thejeshgn** [comment]
moved

**Comment by thejeshgn** [comment]
All the new ACs exists, though with a different spellings
AURIA
BAKULAPUR
BANKAT PURAIHA
BHAISAHI POKHARIA
CHARGAHA
CHUHRI
KURWA MATHIA
RAHIPUR RAMPURVA
