### ISSUE TITLE
Lauriya AC

### ISSUE THREAD

**Issue by NishaT** [datameet/Bihar-AC-Election-Report-Cards#18]
These are the GPs from Lauriya block that are in this AC - the rest have to be moved to another AC
BAHUARWA
BASANT PUR
BASWARIA PARAOU TOLA
BELWA
DHAMAURA
DHARAM PUR
DHOBNI-RAMAULI
DUMRA
DUMRA GOUNAULI
GOBRAURA
LANGRI KATIYA
LAURIYA
MARRIHA
MATHIA
PARAOU TOLA
PERSAUNA
SATHI
SATWARIA
SISWANIA
SITA PUR
SITAPUR-DEURWA

This GP has to be added 
Basopatti

**Comment by thejeshgn** [comment]
@NishaT  moved to which another AC?

**Comment by thejeshgn** [comment]
Moved

**Comment by thejeshgn** [comment]
BASOPATTI already exists in Lauriya sanitation. So dont have to do anything.
