### ISSUE TITLE
Pashchim Champaran - AC Bagaha Converted from PDF to CSV in Dropbox

### ISSUE THREAD

**Issue by NishaT** [datameet/Bihar-AC-Election-Report-Cards#2]
When I finish a AC I'm going to just create an issue so you know

**Comment by thejeshgn** [comment]
@NishaT is it shared with me?

**Comment by thejeshgn** [comment]
Done
https://github.com/datameet/Bihar-AC-Election-Report-Cards/tree/master/data/cleaned/pashchim_champaran/bagaha
