### ISSUE TITLE
Check data for Chanpatiya

### ISSUE THREAD

**Issue by NishaT** [datameet/Bihar-AC-Election-Report-Cards#9]
Says Lauriya

https://github.com/datameet/Bihar-AC-Election-Report-Cards/tree/master/data/cleaned/pashchim_champaran/chanpatiya

**Comment by thejeshgn** [comment]
@NishaT 
It looks all fine to me. Which file exactly? Can you share the screen shot?

**Comment by NishaT** [comment]
No it looks fine to me also maybe some weird github glitch at the time
